# Generated by Django 4.0 on 2021-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Antipolo', 'Antipolo'), ('BGC', 'BGC'), ('Makati', 'Makati'), ('Marikina', 'Marikina'), ('Pasig', 'Pasig'), ('Quezon City', 'Quezon City'), ('San Juan', 'San Juan'), ('Taguig', 'Taguig')], max_length=100),
        ),
    ]
