# Generated by Django 4.0 on 2021-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_state_alter_car_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual'), ('hybrid', 'hybrid')], max_length=50),
        ),
    ]
