# Generated by Django 4.0 on 2021-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Crossover', 'Crossover'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Sports', 'Sports'), ('Truck', 'Truck'), ('Van', 'Van')], max_length=100),
        ),
    ]
