# Generated by Django 4.0 on 2021-12-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Bio-diesel', 'Bio-diesel'), ('Ethanol', 'Ethanol')], max_length=50),
        ),
    ]
